name: atlas

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.3 <4.0.0"
  flutter: ">=3.38.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  google_fonts: ^8.2.1
  dio: ^5.11.1
  logger: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true